
@BaseUrl = https://graph.facebook.com/v19.0/
@AccessToken = EAAIxaH6CnLkBO3w5gHSelHeZAVRjTiFibRmwRZCliBLVsWINjAsd8JAIa2bpRHJ9HXdNoHZCCQvjUID4E5kXqFsZBAzzOwp3RCep3q0zknpkH7u7l3CiGg04OEnsmOmsJvhmU7lpSKoQkBaw0vdXl12BnokZBxIKuw1LZAScZCv66sDDZCZCgZB7MFqchWwgsDFx8JZB0vpT8DxUJKVQPZB9Af8a1e6y9ZCZBER0mAHAZDZD

@PageId = 259323780601906

@UserId = 3604845993111063

@AppId = 617274822270137

@AppSecret = 59743e8c3a9d89ba3098b486cf4e7d7d

@FbExchangeToken=EAAIxaH6CnLkBOwS69ZC5j0Jq1NsnjO47VcPJ44h3IC6QiEUG6iikvasz9Gxfd7erElpdJtpkSoTlU6hXZBBpLdZBZBPtTMyGcujXW0k1TDTuoDsPA6dmtTjzZBh8qQ6p3pZCOp1jIuA60i1fxVVBDEJSTt8PqKOZCWIWCQykOTMHkhjTMDvL2b8WWnIpCTGisUEFA3y3MzXtGkB8QRfWkDq8KKQTsyoUZBfo4hhVd2en


//getUser> getAccestoken> getLongAccessTokenUser> getLongPageAccessToken
# @name getAccessToken 
GET {{BaseUrl}}/oauth/access_token?grant_type=fb_exchange_token&client_id={{AppId}}&client_secret={{AppSecret}}&fb_exchange_token={{FbExchangeToken}}" HTTP/1.1

GET {{BaseUrl}}/oauth/access_token?grant_type=fb_exchange_token&client_id={{AppId}}&client_secret={{AppSecret}}&fb_exchange_token={{FbExchangeToken}}" HTTP/1.1

# POST {{BaseUrl}}/{{PageId}}/feed?message=this is post&access_token={{AccessToken}} HTTP/1.1
# Content-Type: application/json

# @name getAcountUser
# GET {{BaseUrl}}/{{UserId}}/accounts?access_token={{AccessToken}} HTTP/1.1
# Content-Type: application/json

# @name getPageAccessTokens
# GET {{BaseUrl}}/{{UserId}}/accounts?access_token={{AccessToken}} HTTP/1.1
# Content-Type: application/json

# @name getConversationsPage
# GET {{BaseUrl}}/{{PageId}}/conversations?fields=messages{id,message,created_time}&access_token={{AccessToken}} HTTP/1.1
# Content-Type: application/json

# POST {{BaseUrl}}/{{PageId}}/messages HTTP/1.1
# Content-Type: application/json

# {
#   "recipient": {
#     "id": "3604845993111063"
#   },
#   "message": "content message"
# }
